openapi: 3.0.0
info:
  version: 1.0.0
  title: aggregator-svc
  description: 'This is just a proxy (service aggregator) for swapica services, 
  if you need endpoints for these services, see the Swapica services documentation '
servers:
  - url: 'https://api.swapica.io'
    description: TokenD Developer Environment
